# Generated by Django 4.1.7 on 2023-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=6)),
                ('blood_type', models.CharField(choices=[('a+', 'A+'), ('a+', 'A-'), ('b+', 'B+'), ('b+', 'B-'), ('o+', 'O+'), ('o+', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='a+', max_length=4)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
